title: Kikobeats
email: josefrancisco.verdu@gmail.com
description: A millennial doing stuff on internet that ships software every day and builds digital products.
github: kikobeats
author: kikobeats
url: https://kikobeats.com
logo: /images/avatar-glitch.jpg

social:
  name: Kiko Beats
  links:
    - https://x.com/kikobeats
    - https://github.io/kikobeats
    - https://www.linkedin.com/in/kikobeats

twitter:
  username: kikobeats

highlighter: none

permalink: '/:title/'

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-postcss-v2

og_image:
  output_dir: images/og
  base_url: https://og-kikobeats.vercel.app/
  # force: true

defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      comments: false
  - scope:
      path: ''
    values:
      layout: 'default'
  - scope:
      path: 'index.html'
    values:
      layout: 'default'

jekyll-archives:
  enabled:
    - categories
