title: Kikobeats
email: josefrancisco.verdu@gmail.com
description: A millennial doing stuff on internet that ships software every day and builds digital products.
github: kikobeats
author: kikobeats
url: https://kikobeats.com
logo: /images/avatar-glitch.jpg

social:
  name: Kiko Beats
  links:
    - https://x.com/kikobeats
    - https://github.io/kikobeats
    - https://www.linkedin.com/in/kikobeats

twitter:
  username: kikobeats

highlighter: none

permalink: '/:title/'

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-og-image
  - jekyll-sitemap
  - jekyll-postcss-v2

og_image:
  output_dir: images/og
  collections:
    - posts
    - pages
  domain: "kikobeats.com"
  image: "/images/avatar-glitch.jpg"
  header:
    font_family: "Roboto, Bold"
    color: "#333333"
  content:
    font_family: "Roboto, Bold"
    color: "#333333"


defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      comments: false
  - scope:
      path: ''
    values:
      layout: 'default'
  - scope:
      path: 'index.html'
    values:
      layout: 'default'

jekyll-archives:
  enabled:
    - categories
